### ISSUE TITLE
Offline user in voice channel.

### ISSUE THREAD

**Issue by ramazaneris** [revoltchat/vortex#14]
### Offline users in voice channel
If user is exits the revolt or serverbut if don't exit voice channel , user is waiting in the voice channel.
For fix;
- If user left server , user's disconnect with voice channel
- If user exit revolt , user's disconnect with voice channel
Image;
![image](https://user-images.githubusercontent.com/71462879/144709804-e927abbc-a5fe-4de4-b47a-4c398f7df244.png)

**Comment by insertish** [comment]
This project is being rewritten, https://github.com/revoltchat/backend/issues/313.
