### ISSUE TITLE
trouble with cargo build

### ISSUE THREAD

**Issue by nine9797** [revoltchat/vortex#20]
hi , i'm trying to build your code, but i'm getting an error, please help me solve the problem. i do everything on a virtual machine on debian 
error: 
cargo build
   Compiling mediasoup-sys v0.3.1
   Compiling mediasoup v0.9.2
error: failed to build archive: 'libmediasoup-worker.a.p/src_lib.cpp.o': No such file or directory

error: could not compile `mediasoup-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by sivert-io** [comment]
Add this to the bottom of your **Cargo.toml**

`mediasoup-sys = "0.3.3"`


Should now look something like this:
```
. . .

# RTC
mediasoup = "0.9.1"
mediasoup-sys = "0.3.3"
```

That is what fixed the error for me

**Comment by insertish** [comment]
In an effort to clean up the global issue tracker, I'm currently consolidating all issues regarding self-hosting Vortex into https://github.com/revoltchat/vortex/issues/23#issuecomment-1113594595.
