### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by 547555909** [revoltchat/vortex#22]
Compiling mediasoup-sys v0.3.1
error[E0658]: use of unstable library feature 'str_strip': newly added
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mediasoup-sys-0.3.1/build.rs:34:18
   |
34 |                 .strip_suffix("libstdc++.a")
   |                  ^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/67302

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `mediasoup-sys`.

To learn more, run the command again with --verbose.

**Comment by Moonron** [comment]
Find in Cargo.lock

[[package]]
name = "mediasoup-sys"
version = "0.3.1"


And change version to 0.3.2, then run `cargo generate-lockfile` and build it. 

Works for me

**Comment by 547555909** [comment]
您发给我的邮件我已收到，我会尽快回复您的

**Comment by 547555909** [comment]
> 

thank you,i will try it

**Comment by 547555909** [comment]
> cargo generate-lockfile

cargo generate-lockfile
    Updating crates.io index
error: failed to get `base64` as a dependency of package `vortex v0.3.0-alpha.1 (/root/vortex)`

Caused by:
  failed to load source for dependency `base64`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  SSL error: received early EOF; class=Ssl (16); code=Eof (-20)
