### ISSUE TITLE
thread 'main' panicked at 'Missing WS_URL environment variable.: NotPresent', src/util/variables.rs:16:43 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by Cocam123** [revoltchat/vortex#24]
Hello everyone, I decided to create a new issue because I didn't get any answer on the old one (and I think the problem is not related to the old one so I closed it and I made a copy and paste here)

I thank you in advance for all the people who will help me. Here is the message I had sent:

Hello everyone. First of all, sorry for the delay I took. I just wanted to say that my problem concerning Vortex is still not solved. Indeed, when I try to start Vortex, I have the following error that appears:

thread 'main' panicked at 'Missing WS_URL environment variable.: NotPresent', src/util/variables.rs:16:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I searched for several hours to solve this problem but could not find a solution. If you need any particular information (like API link, .env file information or anything else, please let me know)

I thank you in advance for your answer

**Comment by Fwuk** [comment]
does your docker compose look like this? "env_file: .env" 

voice:
   image: revoltchat/vortex:0.3.0-alpha.1
   env_file: .env
   ports:
     - "8080:8080"
     - "10001-11000:10001-11000/tcp"
     - "10001-11000:10001-11000/udp"
 restart: always

**Comment by Cocam123** [comment]
I just saw that the wormhole was not present in the docker-compose. So I will put what you sent and try

**Comment by Cocam123** [comment]
It seems that it still doesn't work
![Capture](https://user-images.githubusercontent.com/64326243/162612730-8ae80dec-ee3b-417c-b8c1-f211436e8874.png)

**Comment by sivert-io** [comment]
Share your .env file and hide your token and replace any IPs with text explaining where it leads to so we can inspect if it is setup correct

**Comment by Cocam123** [comment]
> Share your .env file and hide your token and replace any IPs with text explaining where it leads to so we can inspect if it is setup correct

Hello, here is my .env file
https://drive.google.com/file/d/137N_YRVk56Id9ASNhY0gkja1dfsY00sM/view?usp=sharing

**Comment by sivert-io** [comment]
> > Share your .env file and hide your token and replace any IPs with text explaining where it leads to so we can inspect if it is setup correct
> 
> Hello, here is my .env file https://drive.google.com/file/d/137N_YRVk56Id9ASNhY0gkja1dfsY00sM/view?usp=sharing

Just copy & paste it here in the comments, I will not download anything. 

To make matters clear, your .env file must be setup correctly. Here's an example of how our .env-file is setup in a working Vortex-server:
```
HTTP_HOST=0.0.0.0:8080
WS_URL=wss://OUR_PUBLIC_IP_GOES_HERE
MANAGE_TOKEN=CREATE_A_TOKEN_HERE
RTC_MIN_PORT=1000
RTC_MAX_PORT=1100
DISABLE_RTP=0
RTC_IPS=0.0.0.0,OUR_PUBLIC_IP_GOES_HERE
```

**Comment by Cocam123** [comment]
> > > Share your .env file and hide your token and replace any IPs with text explaining where it leads to so we can inspect if it is setup correct
> > 
> > 
> > Hello, here is my .env file https://drive.google.com/file/d/137N_YRVk56Id9ASNhY0gkja1dfsY00sM/view?usp=sharing
> 
> Just copy & paste it here in the comments, I will not download anything.
> 
> To make matters clear, your .env file must be setup correctly. Here's an example of how our .env-file is setup in a working Vortex-server:
> 
> ```
> HTTP_HOST=0.0.0.0:8080
> WS_URL=wss://OUR_PUBLIC_IP_GOES_HERE
> MANAGE_TOKEN=CREATE_A_TOKEN_HERE
> RTC_MIN_PORT=1000
> RTC_MAX_PORT=1100
> DISABLE_RTP=0
> RTC_IPS=0.0.0.0,OUR_PUBLIC_IP_GOES_HERE
> ```



Here's my configuration (in comments)

```# URL to where the Revolt app is publicly accessible
REVOLT_APP_URL=https://appurl.co.jp

# URL to where the API is publicly accessible
REVOLT_PUBLIC_URL=https://publicurl.co.jp
VITE_API_URL=https://viteapi.co.jp

# URL to where the WebSocket server is publicly accessible
REVOLT_EXTERNAL_WS_URL=wss://excernalwsurl.co.jp

# URL to where Autumn is publicly available
AUTUMN_PUBLIC_URL=https://autumn.co.jp

# URL to where January is publicly available
JANUARY_PUBLIC_URL=http://january.co.jp

# URL to where Vortex is publicly available
 VOSO_PUBLIC_URL=https://voso.revolt.chat

##
## hCaptcha Settings
##

# If you are sure that you don't want to use hCaptcha, set to 1.
REVOLT_UNSAFE_NO_CAPTCHA=1

# hCaptcha API key
# REVOLT_HCAPTCHA_KEY=0x0000000000000000000000000000000000000000

# hCaptcha site key
# REVOLT_HCAPTCHA_SITEKEY=10000000-ffff-ffff-ffff-000000000001


##
## Email Settings
##

# If you are sure that you don't want to use email verification, set to 1.
REVOLT_UNSAFE_NO_EMAIL=1

# SMTP host
 REVOLT_SMTP_HOST=stmp.co.jp

# SMTP username
 REVOLT_SMTP_USERNAME=username

# SMTP password
 REVOLT_SMTP_PASSWORD=password

# SMTP From header
 REVOLT_SMTP_FROM=email address


##
## Application Settings
##

# Whether to only allow users to sign up if they have an invite code
REVOLT_INVITE_ONLY=0

# Maximum number of people that can be in a group chat
REVOLT_MAX_GROUP_SIZE=150

# VAPID keys for push notifications
# Generate using this guide: https://gitlab.insrt.uk/revolt/delta/-/wikis/vapid
# --> Please replace these keys before going into production! <--
REVOLT_VAPID_PRIVATE_KEY=key

REVOLT_VAPID_PUBLIC_KEY=key


##
## Autumn configuration
##

# S3 Region
AUTUMN_S3_REGION=minio

# S3 Endpoint
AUTUMN_S3_ENDPOINT=http://minio:9000

# MinIO Root User
MINIO_ROOT_USER=minioautumn

# MinIO Root Password
MINIO_ROOT_PASSWORD=minioautumn

# AWS Access Key ID (auto-filled if present above)
# AWS_ACCESS_KEY_ID=minioautumn

# AWS Secret Key (auto-filled if present above)
# AWS_SECRET_ACCESS_KEY=minioautumn


##
## Vortex configuration
##
 HTTP_HOST=wss://0.0.0.0:8080 #directed to port 8080
 WS_URL=wss://0.0.0.0:8080 #also directed to port 8080 (I don't know if it's a mistake because I think this option is an option to listen to port 8080 that's why I put the same)
 RTC_MIN_PORT=10000 #min port
 RTC_MAX_PORT=11000 #max port
 DISABLE_RTP=0
 RTC_IPS=0.0.0.0,public ip```

**Comment by Fwuk** [comment]
ws_url should be the same as your voso public url. and im not sure if it matters but try removing all the spaces in front of the parameters

here is an example of my .env file

##
## Vortex configuration
##

WS_URL=wss://voso.domain.net
RTC_IPS=0.0.0.0,PUBLICIP
RTC_MIN_PORT=10001
RTC_MAX_PORT=11000
MANAGE_TOKEN=TOKEN
VOSO_MANAGE_TOKEN=TOKEN
DISABLE_RTP=1

**Comment by Cocam123** [comment]
> ws_url should be the same as your voso public url. and im not sure if it matters but try removing all the spaces in front of the parameters
> 
> here is an example of my .env file
> 
> ## Vortex configuration
> WS_URL=wss://voso.domain.net RTC_IPS=0.0.0.0,PUBLICIP RTC_MIN_PORT=10001 RTC_MAX_PORT=11000 MANAGE_TOKEN=TOKEN VOSO_MANAGE_TOKEN=TOKEN DISABLE_RTP=1

Hello, it still doesn't work :/

**Comment by insertish** [comment]
In an effort to clean up the global issue tracker, I'm currently consolidating all issues regarding self-hosting Vortex into https://github.com/revoltchat/vortex/issues/23#issuecomment-1113594595.
