### ISSUE TITLE
error: failed to run custom build command for `mediasoup-sys v0.3.1`

### ISSUE THREAD

**Issue by Kensai666** [revoltchat/vortex#26]
### What happened?

[error.txt](https://github.com/revoltchat/vortex/files/9236228/error.txt)
Please see attached the error I keep getting.

I've tried to do as the error suggests, installing pip, meson, and setuptools directly into the mediasoup folders, but then when using "Cargo Build", the compiling hangs at mediasoup-sys(build).

Any help would be great!

**Comment by eli-schwartz** [comment]
What's the output of `cargo build -vv`?

**Comment by Kensai666** [comment]
> What's the output of `cargo build -vv`?
[error-vv.txt](https://github.com/revoltchat/vortex/files/9242007/error-vv.txt)
Please see the attached error when running `cargo build -vv`

**Comment by insertish** [comment]
Vortex is currently being rewritten and I'm now starting to move my work into this repository so I'm also cleaning up issues while I'm at it. This project will cease to use mediasoup-sys in the new branch and the current branch is no longer maintained.
