### ISSUE TITLE
bug: failed to run custom build command for `mediasoup-sys v0.2.5 (https://github.com/fatalerrorcoded/mediasoup#348ad1f7)` (vortex 0.3.0 alpha)

### ISSUE THREAD

**Issue by Cocam123** [revoltchat/vortex#28]
### What happened?

I know that this is an alpha version and that bugs happen, however, I wanted to report this problem during the installation with the cargo build command.

I also updated cargo but nothing happens

![image](https://user-images.githubusercontent.com/64326243/197479925-ab1140da-42a4-422d-9a67-57f7ce34cf16.png)

**Comment by infiniwave** [comment]
@insertish and Revolt development is working on a rewrite on the `vortex` branch. The version that uses Mediasoup is the older version that is known to cause issues on certain platforms so I think it is better that you wait.

**Comment by insertish** [comment]
Closing due to rewrite, https://github.com/revoltchat/backend/issues/313.
