### ISSUE TITLE
Add support for screen sharing

### ISSUE THREAD

**Issue by ekrekeler** [revoltchat/vortex#4]
Currently it seems like there is no support for screen sharing in a voice chat. This is the one thing that is keeping me from migrating away from Discord.

Are there any plans to incorporate this in a future release?

**Comment by insertish** [comment]
It is planned but it may take a while before it ends up being implemented.

**Comment by nerrixde** [comment]
revoltchat/vortex#9 is in "done", while it's not done just closed bc dupe

**Comment by nerrixDE** [comment]
cc @insertish

**Comment by insertish** [comment]
Removing issues so they can be reorganised when this project is ready to go ahead again, https://github.com/revoltchat/backend/issues/313.
