### ISSUE TITLE
RTC_IPS expects public IP Address, usage of hostname not possible

### ISSUE THREAD

**Issue by kiguigui** [revoltchat/vortex#7]
Hello there,

at first: thanks for your great work with revolt. Its great!

I have the issue that vortex running as docker container is expecting the environment variable RTC_IPS with must contain an IP Address. 0.0.0.0 is not accepted as the only content since this is the address the voice clients are connecting to (seems so). So I'm using RTC_IPS = 0.0.0.0,1.2.3.4 (my public IP Address). This is working so far. But since I don't have an static public IP, I have to change it every couple of Days. When entering a hostname like a dedyn domain name it doesn't work.

Is it possible to make RTC_IPS accepting FQDNs instead of IP Addresses?

**Comment by insertish** [comment]
Removing issues so they can be reorganised when this project is ready to go ahead again, https://github.com/revoltchat/backend/issues/313.
